In [1]:
#GAN architecture
import tensorflow as tf
from tensorflow import keras as ke
LR_shape = (32,32,3)
s = 2
HR_shape = (LR_shape[0]*s,LR_shape[1]*s,3)


def Generator(LR_shape = LR_shape,s = s):
    model = ke.Sequential()
    # model.add(ke.layers.Conv2D(3,(64,64),strides=(4,4),input_shape=LR_shape,activation='relu'))
    # model.add(ke.layers.MaxPool2D())
    model.add(ke.layers.Flatten(input_shape=(LR_shape)))
    model.add(ke.layers.Dense(LR_shape[0]*LR_shape[1]*3,activation='relu'))
    model.add(ke.layers.Dense(LR_shape[0]*s*LR_shape[1]*s*3,activation='sigmoid'))
    HR_shape = (LR_shape[0]*s,LR_shape[1]*s,3)
    model.add(ke.layers.Reshape(HR_shape))
    return model

In [2]:
# drive access
from google.colab import drive
drive.mount('/content/gdrive')


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [3]:
# making low res images
import numpy as np
from PIL import Image
import numpy

def get_img_arr(path: str):
    img = np.array(Image.open(path))
    return img

def high_to_lowres(img_num: str):
    img_path = "/content/gdrive/MyDrive/00000/"+img_num+".png" #replace with location of data
    img_arr = get_img_arr(img_path)
    img_arr = img_arr.astype(np.float64)
    lr_img_arr = np.zeros((512,512,3))
    for k in range(lr_img_arr.shape[2]):
        for i in range(lr_img_arr.shape[0]):
            for j in range(lr_img_arr.shape[1]):
                lr_img_arr[i,j,k] = (img_arr[2*i,2*j,k] + img_arr[2*i,2*j+1,k] + img_arr[2*i+1,2*j,k] + img_arr[2*i+1,2*j+1,k])/4
    lr_img = Image.fromarray(lr_img_arr.astype(np.uint8))
    lr_img.save("/content/gdrive/MyDrive/lr_imgs/"+img_num+"_lr.png") #replace with desired location of LR imgs

img_num = '00000'
img0 = get_img_arr("/content/gdrive/MyDrive/00000/"+img_num+".png")
img0.shape

(1024, 1024, 3)

In [ ]:
# apply above high_to_lowres function on '00000' to '01000' this is for generating low res images
#only run this if you want to generate the low res data

for i in range(0,1000):
    img_num = str(i).zfill(5)
    high_to_lowres(img_num)

KeyboardInterrupt: ignored

In [4]:
# model creation

gen = Generator()
gen.compile(loss="mean_squared_error", optimizer='adam', metrics=['accuracy'])
gen.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 3072)              0         
                                                                 
 dense (Dense)               (None, 3072)              9440256   
                                                                 
 dense_1 (Dense)             (None, 12288)             37761024  
                                                                 
 reshape (Reshape)           (None, 64, 64, 3)         0         
                                                                 
Total params: 47201280 (180.06 MB)
Trainable params: 47201280 (180.06 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [5]:
import random as rd
import time

def pick_box(img:np.ndarray,box_size:int):
    img_shape = img.shape
    x_max, y_max = img_shape[0] - box_size, img_shape[1] - box_size
    x, y = rd.randint(0,x_max), rd.randint(0,y_max)
    box = img[x:x+box_size,y:y+box_size,:] #check shape of box
    assert box.shape == (box_size,box_size,3)
    return box

def make_real_batch_arr(img_names:list):
    boxes_lst = []
    for img_num in img_names:
        img_hr = get_img_arr("/content/gdrive/MyDrive/00000/"+img_num+".png") #replace with location of data
        box = pick_box(img_hr,HR_shape[0])
        boxes_lst.append(box)
    boxes_arr = np.array(boxes_lst)
    return boxes_arr/255

def gen_input_batch_arr(img_names:list):
    boxes_lst = []
    for img_num in img_names:
        img_lr = get_img_arr("/content/gdrive/MyDrive/lr_imgs/"+img_num+"_lr.png")#replace with location of LR images
        box = pick_box(img_lr,LR_shape[0])
        boxes_lst.append(box)
    boxes_arr = np.array(boxes_lst)
    return boxes_arr/255

def real_batch_to_lr(batch_arr:np.ndarray):
    lr_batch = []
    for n in range(batch_arr.shape[0]):
        img_arr = batch_arr[n]
        img_arr = img_arr.astype(np.float64)
        lr_img_arr = np.zeros((32,32,3))
        for k in range(lr_img_arr.shape[2]):
            for i in range(lr_img_arr.shape[0]):
                for j in range(lr_img_arr.shape[1]):
                    lr_img_arr[i,j,k] = (img_arr[2*i,2*j,k] + img_arr[2*i,2*j+1,k] + img_arr[2*i+1,2*j,k] + img_arr[2*i+1,2*j+1,k])/4
        lr_batch.append(lr_img_arr)
    lr_batch_arr = np.array(lr_batch)
    return lr_batch_arr

def make_name_batches(img_names:list,batch_size:int):
    batches = []
    for i in range(len(img_names)//batch_size):
        batches.append(img_names[i*batch_size:(i+1)*batch_size])
    return batches

In [18]:
!pip install Pillow --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 12.7 MB/s eta 0:00:00
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.31.6 requires pillow<10.1.0,>=8.3.2, but you have pillow 10.1.0 which is incompatible.


In [6]:
start = time.time()

no_of_epochs = 10
batch_size = 100

real = np.ones((batch_size,1))
fake = np.zeros((batch_size,1))


img_names = [str(i).zfill(5) for i in range(900)]

for epoch in range(1,no_of_epochs+1):
    print("Epoch: ",epoch)
    rd.shuffle(img_names)
    batches = make_name_batches(img_names,batch_size)
    for batch in batches:
        real_batch_arr = make_real_batch_arr(batch)
        gen_input_arr = real_batch_to_lr(real_batch_arr)
        loss = gen.train_on_batch(gen_input_arr,real_batch_arr)
        print(loss)
gen.save("/content/gdrive/MyDrive/model/L2model")
end = time.time()
print("Time Taken: ",end-start)

Epoch:  1
[0.07387447357177734, 0.3461352586746216]
[0.07007425278425217, 0.46442872285842896]
[0.07752908021211624, 0.6123461723327637]
[0.07681715488433838, 0.7503027319908142]
[0.06417519599199295, 0.8020995855331421]
[0.07125259190797806, 0.83697509765625]
[0.06435690075159073, 0.8102734088897705]
[0.06384465098381042, 0.7793359160423279]
[0.07031507790088654, 0.7793188691139221]
Epoch:  2
[0.06741200387477875, 0.7810864448547363]
[0.07100191712379456, 0.7514477372169495]
[0.05752624571323395, 0.7878271341323853]
[0.06221716105937958, 0.7540649175643921]
[0.06250092387199402, 0.7903100848197937]
[0.04792608693242073, 0.8453222513198853]
[0.05933758616447449, 0.8359130620956421]
[0.06282078474760056, 0.7939916849136353]
[0.055969852954149246, 0.8198486566543579]
Epoch:  3
[0.05762610584497452, 0.7796899676322937]
[0.055313412100076675, 0.770678699016571]
[0.0582079142332077, 0.7950049042701721]
[0.04283444955945015, 0.878125011920929]
[0.06521002948284149, 0.8126489520072937]
[0.061

In [ ]:
# code to load the saved model

gen = ke.models.load_model("/content/gdrive/MyDrive/model/L2model")


In [7]:
# prediction

def enhance(generator,img_lr:np.ndarray):
    img_shape = (1024,1024,3)
    img_hr_arr = np.zeros(img_shape)
    box_size = LR_shape[0]
    input_boxes = []
    for x in range(0,512,box_size):
        for y in range(0,512,box_size):
            lr_box = img_lr[x:x+box_size,y:y+box_size,:]
            input_boxes.append(lr_box)
    input_arr = np.array(input_boxes)
    output_arr = generator.predict(input_arr)
    print(output_arr[0])
    n = 0
    for x in range(0,1024,s*box_size):
        for y in range(0,1024,s*box_size):
            img_hr_arr[x:x+s*box_size,y:y+s*box_size,:] = output_arr[n]
            n += 1
    img_hr_arr = 255*img_hr_arr
    print(img_hr_arr.shape)
    img_hr = Image.fromarray(img_hr_arr.astype(np.uint8))
    return img_hr


In [8]:
img_num = '00000'
img_lr = get_img_arr("/content/gdrive/MyDrive/lr_imgs/"+img_num+"_lr.png") #replace with location of LR imgs
img_hr = enhance(gen,img_lr)
img_hr.save("test_enhancedL1_img.png")

8/8 [==============================] - 0s 3ms/step
[[[0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 8.3972373e-38 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  ...
  [0.0000000e+00 2.8949433e-22 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]]

 [[0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  ...
  [0.0000000e+00 8.2080891e-33 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 1.0135649e-22 1.0000000e+00]]

 [[0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  ...
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 9.5268218e-17 1.0000000e+00]]

 ...

 [[0.0000000e+00 0.0000000e+00 1.0000000e+00]
  [0.0000000e+00 0.0000000e+00 1.0000000e+00]

In [ ]:
gen.get_weights()

[array([[-0.03474364, -0.006733  ,  0.03319844, ...,  0.01608609,
         -0.01078267,  0.02810628],
        [-0.00169752,  0.01050872,  0.00872461, ...,  0.0073162 ,
         -0.02205878,  0.01315914],
        [ 0.0123641 , -0.01013493,  0.03077506, ...,  0.00775197,
         -0.03343421, -0.01918154],
        ...,
        [-0.03029131, -0.02152351, -0.00211731, ..., -0.0057497 ,
         -0.03472714,  0.00309255],
        [-0.00070133,  0.01194959, -0.01720232, ...,  0.02334778,
         -0.01624081, -0.00689805],
        [-0.02688782,  0.01091124, -0.00908104, ...,  0.02086956,
         -0.00117854,  0.00680057]], dtype=float32),
 array([-0.03245052,  0.00489448,  0.03545408, ...,  0.03727034,
        -0.0387821 ,  0.03745752], dtype=float32),
 array([[ 0.01835281,  0.01430098,  0.00461422, ..., -0.00880362,
         -0.01320824,  0.00650637],
        [ 0.00386935,  0.00806288, -0.00469451, ...,  0.00903872,
         -0.00903917,  0.00913495],
        [-0.01000282, -0.00889328, -0.